name: 'publish-eslint-config'

on:
  push:
    branches:
      - master
    paths:
      - 'packages/eslint-config/**'

jobs:
  publish:
    name: publish-eslint-config
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
      - name: publish
        run: npm publish --access public
        working-directory: packages/eslint-config
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
