name: 'publish-editor-config'

on:
  push:
    branches:
      - master
    paths:
      - 'packages/editor-config/**'

jobs:
  publish:
    name: publish-editor-config
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
      - name: version
        run: npm --no-git-tag-version version "1.0.$GITHUB_RUN_NUMBER" -m "Upgrade to new version"
        working-directory: packages/editor-config
      - name: publish
        run: npm publish --access public
        working-directory: packages/editor-config
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
